/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Boostable"): TruffleContracts.BoostableContract;
      require(
        name: "CosBoostableLib"
      ): TruffleContracts.CosBoostableLibContract;
      require(name: "CosToken"): TruffleContracts.CosTokenContract;
      require(name: "DummyERC721"): TruffleContracts.DummyERC721Contract;
      require(
        name: "DummyERC721Receiver"
      ): TruffleContracts.DummyERC721ReceiverContract;
      require(
        name: "EIP712Boostable"
      ): TruffleContracts.EIP712BoostableContract;
      require(name: "ERC165"): TruffleContracts.ERC165Contract;
      require(name: "ERC721"): TruffleContracts.ERC721Contract;
      require(name: "Heroes"): TruffleContracts.HeroesContract;
      require(
        name: "IBoostableERC20"
      ): TruffleContracts.IBoostableERC20Contract;
      require(name: "IERC165"): TruffleContracts.IERC165Contract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IERC721"): TruffleContracts.IERC721Contract;
      require(
        name: "IERC721Receiver"
      ): TruffleContracts.IERC721ReceiverContract;
      require(name: "IOptIn"): TruffleContracts.IOptInContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Pets"): TruffleContracts.PetsContract;
      require(
        name: "ProtectedBoostable"
      ): TruffleContracts.ProtectedBoostableContract;
      require(
        name: "ProtectedBoostableLib"
      ): TruffleContracts.ProtectedBoostableLibContract;
    }
  }
}
